import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const assetsDir = path.join(__dirname, "../Assets/Icons");
const outFile = path.join(assetsDir, "icons.css");

// Keep legacy variable names currently used by FileTree/style.css.
const NAME_ALIASES = {
  "folder-icon": "folder",
  "folder-icon-grid": "f-grid",
};


const REMOVE_ATTRS = [
  "version",
  "class",
  "data-name",
  "version",
  "xml:space",
  "enable-background",
];

function stripCommentsAndDeclarations(svg) {
  return svg
    .replace(/<\?xml[\s\S]*?\?>/gi, "")
    .replace(/<!doctype[\s\S]*?>/gi, "")
    .replace(/<!--[\s\S]*?-->/g, "");
}

function stripNonEssentialAttrs(svg) {
  let out = svg;

  for (const attr of REMOVE_ATTRS) {
    const attrPattern = new RegExp(`\\s${attr}=("[^"]*"|'[^']*')`, "gi");
    out = out.replace(attrPattern, "");
  }

  // Root width/height are usually unnecessary for viewBox-driven data-uri icons.
  out = out.replace(/<svg\b([^>]*?)\swidth=("[^"]*"|'[^']*')/i, "<svg$1");
  out = out.replace(/<svg\b([^>]*?)\sheight=("[^"]*"|'[^']*')/i, "<svg$1");

  // Remove extra whitespace between tags and trim.
  out = out.replace(/>\s+</g, "><").trim();

  return out;
}

function toDataUri(svg) {
  const compact = svg.replace(/\s+/g, " ").trim();

  // Minimal escaping for CSS url('...') data URIs:
  // keep SVG markup readable, only escape characters that commonly break CSS/url parsing.
  const escaped = compact
    .replace(/%/g, "%25")
    .replace(/#/g, "%23")
    .replace(/'/g, "%27")
    .replace(/\r?\n/g, " ");

  return `data:image/svg+xml,${escaped}`;
}

function varNameFromFile(fileName) {
  const base = fileName.replace(/\.svg$/i, "");
  return NAME_ALIASES[base] || base;
}

async function main() {
  const entries = await fs.readdir(assetsDir, { withFileTypes: true });
  const svgFiles = entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".svg"))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  if (svgFiles.length === 0) {
    throw new Error(`No SVG files found in ${assetsDir}`);
  }

  const declarations = [];
  const defs = [];
  for (const fileName of svgFiles) {
    const absPath = path.join(assetsDir, fileName);
    const raw = await fs.readFile(absPath, "utf8");
    const cleaned = stripNonEssentialAttrs(stripCommentsAndDeclarations(raw));

    // Write cleaned SVG back to disk so source files stay optimized.
    await fs.writeFile(absPath, `${cleaned}\n`, "utf8");

    const varName = varNameFromFile(fileName);
    const dataUri = toDataUri(cleaned);
    declarations.push(`    --i-${varName}: url('${dataUri}');`);
    defs.push(`[i="${varName}"], [${varName}] { --i-bg: var(--i-${varName}); }`);
  }

  const css = [
    "/* Auto-generated by build-icons-css.mjs. Do not edit manually. */",
    ":root, :host {",
    ...declarations,
    "}",
    "",
    ...defs,
`i-bw {
    background-color: currentColor;
    mask-image: var(--i-bg);
    display: inline-block;
    width: 1.2em;
    height: 1.2em;
    mask-position: center;
    mask-size: contain;
    mask-repeat: no-repeat;
}
i-c {
    background-image: var(--i-bg);
    display: inline-block;
    width: 1.2em;
    height: 1.2em;
    background-position: center;
    background-size: contain;
    background-repeat: no-repeat;
}`
  ].join("\n");

  await fs.writeFile(outFile, css, "utf8");

  console.log(`Updated ${path.relative(__dirname, outFile)} with ${svgFiles.length} SVG icons.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
