import "../bg-img.js";
import "../Access/access-buttons.js"
import { SvgPlus, Vector } from "../../SvgPlus/4.js";
import { Icon } from "../icons.js";

/**
* This file is auto-generated by build-grid-icon-themes.js. Do not edit directly.
* @typedef {Object} GridIconTheme
* @property {"plain"|"folder"} card - The type of card to use for this theme.
* @property {GridIconColorThemes} theme - The color theme to use for this grid icon.
*
* @typedef {GridIconColorThemes|GridIconTypeThemes|GridIconTheme} GridIconType
*/
const GRID_ICON_THEMES = {
    "lightRed": {
        "card": "plain",
        "theme": "lightRed"
    },
    "topic-lightRed": {
        "card": "folder",
        "theme": "lightRed"
    },
    "darkRed": {
        "card": "plain",
        "theme": "darkRed"
    },
    "topic-darkRed": {
        "card": "folder",
        "theme": "darkRed"
    },
    "lightOrange": {
        "card": "plain",
        "theme": "lightOrange"
    },
    "topic-lightOrange": {
        "card": "folder",
        "theme": "lightOrange"
    },
    "darkOrange": {
        "card": "plain",
        "theme": "darkOrange"
    },
    "topic-darkOrange": {
        "card": "folder",
        "theme": "darkOrange"
    },
    "lightGold": {
        "card": "plain",
        "theme": "lightGold"
    },
    "topic-lightGold": {
        "card": "folder",
        "theme": "lightGold"
    },
    "darkGold": {
        "card": "plain",
        "theme": "darkGold"
    },
    "topic-darkGold": {
        "card": "folder",
        "theme": "darkGold"
    },
    "lightGreen": {
        "card": "plain",
        "theme": "lightGreen"
    },
    "topic-lightGreen": {
        "card": "folder",
        "theme": "lightGreen"
    },
    "darkGreen": {
        "card": "plain",
        "theme": "darkGreen"
    },
    "topic-darkGreen": {
        "card": "folder",
        "theme": "darkGreen"
    },
    "lightTeal": {
        "card": "plain",
        "theme": "lightTeal"
    },
    "topic-lightTeal": {
        "card": "folder",
        "theme": "lightTeal"
    },
    "darkTeal": {
        "card": "plain",
        "theme": "darkTeal"
    },
    "topic-darkTeal": {
        "card": "folder",
        "theme": "darkTeal"
    },
    "lightBlue": {
        "card": "plain",
        "theme": "lightBlue"
    },
    "topic-lightBlue": {
        "card": "folder",
        "theme": "lightBlue"
    },
    "darkBlue": {
        "card": "plain",
        "theme": "darkBlue"
    },
    "topic-darkBlue": {
        "card": "folder",
        "theme": "darkBlue"
    },
    "lightIndigo": {
        "card": "plain",
        "theme": "lightIndigo"
    },
    "topic-lightIndigo": {
        "card": "folder",
        "theme": "lightIndigo"
    },
    "darkIndigo": {
        "card": "plain",
        "theme": "darkIndigo"
    },
    "topic-darkIndigo": {
        "card": "folder",
        "theme": "darkIndigo"
    },
    "lightPurple": {
        "card": "plain",
        "theme": "lightPurple"
    },
    "topic-lightPurple": {
        "card": "folder",
        "theme": "lightPurple"
    },
    "darkPurple": {
        "card": "plain",
        "theme": "darkPurple"
    },
    "topic-darkPurple": {
        "card": "folder",
        "theme": "darkPurple"
    },
    "action": {
        "card": "plain",
        "theme": "action"
    },
    "topic-action": {
        "card": "folder",
        "theme": "action"
    },
    "white": {
        "card": "plain",
        "theme": "white"
    },
    "topic-white": {
        "card": "folder",
        "theme": "white"
    },
    "topic": {
        "card": "folder",
        "theme": "topic"
    },
    "normal": {
        "card": "plain",
        "theme": "normal"
    },
    "topic-normal": {
        "card": "folder",
        "theme": "normal"
    },
    "starter": {
        "card": "plain",
        "theme": "starter"
    },
    "topic-starter": {
        "card": "folder",
        "theme": "starter"
    },
    "noun": {
        "card": "plain",
        "theme": "noun"
    },
    "topic-noun": {
        "card": "folder",
        "theme": "noun"
    },
    "adjective": {
        "card": "plain",
        "theme": "adjective"
    },
    "topic-adjective": {
        "card": "folder",
        "theme": "adjective"
    },
    "verb": {
        "card": "plain",
        "theme": "verb"
    },
    "topic-verb": {
        "card": "folder",
        "theme": "verb"
    },
    "emphasis": {
        "card": "plain",
        "theme": "emphasis"
    },
    "topic-emphasis": {
        "card": "folder",
        "theme": "emphasis"
    }
};

/**
 * GridIconSymbol can be a string or an object defining the icon symbol.
 * If a string, it can be an icon name or a URL.
 * If an object, it can have a 'url' property for the image URL or a 'text' property for text content.
 * @typedef {IconName | {url: string} | {text: string}} IconSymbol
 * @see /Utilities/Icons/icons-library.js
 */

/**
 * @typedef {Object} GridIconOptions
 * @property {string} [type] - The card type 
 * @property {string} [colorTheme] - The color theme for the icon
 * @property {string} [accessGroup] - The access group for the icon, used for grouping icons together.
 * @property {string} displayValue - The text to display below the icon.
 * @property {string} [subtitle] - The icon symbol, can be a string or an object with a url.
 * @property {IconSymbol} [symbol] - The icon symbol, see above.
 * @property {boolean} [hidden] - If true, the icon will be hidden.
 * @property {boolean} [disabled] - If true, the icon will be disabled and slightly see through.
 * @property {boolean} [displayOnly] - If true, the icon will not be interactive.
 * @property {Object.<string, Function>} [events] - An object mapping event names to event handler functions.
 */


const CARD_RENDERERS = {
    F45RAD: 1 / Math.tan( 3 * Math.PI / 8 ),
    plain(size, border, borderRadius) {
        let inSize = size.sub(border);
        let g = borderRadius;;
        return `
            <rect class = "card" x = "${border/2}" y = "${border/2}" width = "${inSize.x}"  height = "${inSize.y}" rx = "${g}" ry = "${g}" />
            
            <rect class = "card for-hover" x = "${border/2}" y = "${border/2}" width = "${inSize.x}"  height = "${inSize.y}" rx = "${g}" ry = "${g}" />
            <rect class = "outline for-hover" stroke-width = "${border}"  x = "${border/2}" y = "${border/2}" width = "${inSize.x}"  height = "${inSize.y}" rx = "${g}" ry = "${g}" />
            
            <rect class = "card for-active" x = "${border/2}" y = "${border/2}" width = "${inSize.x}"  height = "${inSize.y}" rx = "${g}" ry = "${g}" />
            <rect class = "outline for-active" stroke-width = "${border}"  x = "${border/2}" y = "${border/2}" width = "${inSize.x}"  height = "${inSize.y}" rx = "${g}" ry = "${g}" />
            `
    },
    
    folder(size, border, borderRadius) {
        let inSize = size.sub(border);
        let g = borderRadius;
        let w = inSize.x;
        let y = this.F45RAD

    
        g = Math.min(w / (3 + 2 * y), g);
        let d0 = w - g * (3 + 2 * y);
        let b = d0 * 0.45
    
        let p1 = new Vector(border/2, border/2 + 2*g);
        let p2 = p1.addV(-g);
        let p3 = p2.add(g, -g);
        let p4 = p3.addH(b);

        let d1 = y*g/Math.sqrt(2)
        let p5 = p4.addH(y * g).add(d1)

        let p7 = p4.add(g * (1 + 2 * y), g)
        let p6 = p7.addH(-y * g).sub(d1)
        let p9 = p1.addH(w)
        let p8 = p9.sub(g)

        let h = inSize.y;
        let p10 = p9.addV(h - 3 * g);
        let p11 = p10.add(-g, g);

        let p13 = p1.addV(h - 3 * g);
        let p12 = p13.add(g, g);


        g = new Vector(g, g);
        let tabPath = `M${p1}L${p2}A${g},0,0,1,${p3}L${p4}A${g},0,0,1,${p5}L${p6}A${g},0,0,0,${p7}L${p8}A${g},0,0,1,${p9}Z`;
        let card = `M${p9}L${p10}A${g},0,0,1,${p11}L${p12}A${g},0,0,1,${p13}L${p1}Z`;
        let outline = `M${p1}L${p2}A${g},0,0,1,${p3}L${p4}A${g},0,0,1,${p5}L${p6}A${g},0,0,0,${p7}L${p8}A${g},0,0,1,${p9}L${p10}A${g},0,0,1,${p11}L${p12}A${g},0,0,1,${p13}Z`;
        return  `
    
                <path class = "card" d = "${card}" />
                <path class = "tab" d = "${tabPath}" />
                
                <path class = "card for-hover" d = "${card}" />
                <path class = "tab for-hover" d = "${tabPath}" />
                <path class = "outline for-hover" stroke-width = "${border}"  d = "${outline}" />
                
                <path class = "card for-active" d = "${card}" />
                <path class = "tab for-active" d = "${tabPath}" />
                <path class = "outline for-active" stroke-width = "${border}" d = "${outline}" />
                `
    }
};

/** A GridIconSymbol represents the image from a grid icon. */
class GridIconSymbol extends SvgPlus{
    /** 
     * @param {IconSymbol} symbol
     * @param {boolean} [useBackgroundImg=false] - If true, use a background image instead of an img element.
     * */
    constructor(symbol, useBackgroundImg = false){
        super("div");
        this.class = "symbol";
       
        let url = symbol;
        if (symbol !== null && typeof symbol == "object" && "url" in symbol) {
            url = symbol.url;
        }

        if (typeof url === "string") {
            let isURL = (url.startsWith("http://") || url.startsWith("https://"));
            if (isURL) {
                this.createChild("bg-img", {
                    src: url,
                });
            } else {
                this.createChild(Icon, {}, url)
                this.toggleAttribute("icon", true);
            }
        } 
    }
}

class GridCard extends SvgPlus { 
    #type = "plain";
    /**
     * @param {HTMLElement|string} el - The element or tag name to create for the grid card.
     * @param {string} type - The type of the grid card.
     * @param {string} colorTheme - The color theme for the grid card.
     */
    constructor(el, type, colorTheme) {
        super(el);
        this.class = "grid-icon";

        this.cardIcon = this.createChild("svg", {class: "card-icon"});
        this.content = this.createChild("div", {class: "content"});

        let rs = new ResizeObserver(this.onresize.bind(this));
        rs.observe(this);

        this.type = type;
        this.colorTheme = colorTheme || "white";
    }

    /** 
     * Disables pointer events and applies disabled styles to the icon.
     * @param {boolean} displayOnly 
     * */
    set displayOnly(displayOnly) {
        this.toggleAttribute("i-display-only", displayOnly);
    }

    /** @return {boolean} */
    get displayOnly() {
        return this.hasAttribute("i-display-only");
    }

    /** 
     * Disables the active effect on the icon, which normally changes the icon's appearance when clicked.
     * @param {boolean} type 
     * */
    set disableActiveEffect(disable) {
        this.toggleAttribute("i-disable-active", disable);
    }

    /** @return {boolean} */
    get disableActiveEffect() {
        return this.hasAttribute("i-disable-active");
    }
    
    /** 
     * Disables the hover effect on the icon, which normally changes the icon's appearance when hovered over.
     * @param {boolean} disable */
    set disableHoverEffect(disable) {
        this.toggleAttribute("i-disable-hover", disable);
    }

    /** @return {boolean} */
    get disableHoverEffect() {
        return this.hasAttribute("i-disable-hover");
    }

    /** 
     * Disables the icon, making it non-interactive and applying disabled styles.
     * I.e. slightly see through and no active effect.
     * @param {boolean} disabled */
    set disabled(disabled) {
        this.toggleAttribute("i-disabled", disabled);
        this._disabled = disabled;
    }

    /** @return {boolean} */
    get disabled() {
        return this._disabled;
    }

    /** @param {string} type */
    set type(typeValue) {
        typeValue = typeValue in CARD_RENDERERS ? typeValue : "plain";
        this.cardRenderer = (...a) => CARD_RENDERERS[typeValue](...a)
        this.setAttribute("card", typeValue);
        this.#type = typeValue;
        this.onresize();
    }

    get type(){
        return this.#type
    }

    get colorTheme() {
        return this.getAttribute("color-theme");
    }
    set colorTheme(theme) {
        this.setAttribute("color-theme", theme);
    }

     // Called when the size of the icon changes.
    onresize(e){
        if (!e) {
            e = [{contentRect: this.getBoundingClientRect()}];
        }
        let bbox = e[0]?.contentRect;
        if (bbox) {
            let {width, height} = bbox;
            this.styles = {
              "--width": width + "px",
              "--height": height + "px"
            }
            if (width > 0 && height > 0) {
                let size = new Vector(width, height);
                this.cardIcon.props = {
                    viewBox: `0 0 ${size.x} ${size.y}`,      // Update the svg viewBox.
                    content: this.cardRenderer(
                      size, 
                      this.getCardBorderWidth(width, height), 
                      this.getCardBorderRadius(width, height)
                    ) // Recompute the svg content.
                };
            }
        }
        return [bbox.width, bbox.height];
    }

    getCardBorderRadius(w, h) {
      return h/20;
    }
    getCardBorderWidth() {
      return window.innerWidth < 450 ? 2 : 4;
    }


    static getCardRenderer(type) {
      if (CARD_RENDERERS[type] instanceof Function) {
        return CARD_RENDERERS[type].bind(CARD_RENDERERS);
      }
    }
}

class TextValue extends SvgPlus {
    constructor() {
        super("div");
    }

    set(value) {
        this.innerHTML = "";
        if (typeof value === "string" && value.length > 0) {
            this.createChild("span").textContent = value;
        }
    }
}

/** A GridIcon represents an item from a topic. */
class GridIcon extends GridCard {
    symbolLoaded = false;

    /** @type {?TextValue} */
    subtitleElement = null;

    /** @type {TextValue} */
    displayValueElement = null;

    /** 
     * @param {GridIconOptions} item 
     * @param {string} accessGroup
     * */
    constructor(item, accessGroup) {
        try {
            super("access-button", item.type, item.colorTheme);
        } catch (e) {
            console.error("Error creating GridIcon with type:", item);
            throw e;
        }
        this.group = accessGroup || item.accessGroup || "default";
        this.item = item;
    
        // Toggle attribute 'i-hidden' if icon is hidden.
        this.toggleAttribute("i-hidden", !!item.hidden);


        // Add symbol to content box.
        if ("symbol" in item) {
           this.symbol = item.symbol;
        } else {
            this.symbolLoaded = true;
        }
        
        // Add text box with display value to content box.
        this.displayValueElement = this.makeDisplayValueElement();
        this.displayValue = item.displayValue || "";

        this.subtitle = item.subtitle;
       
        this.disabled = item.disabled || false;
        this.displayOnly = item.displayOnly || false;

        this.toggleAttribute("label-at-bottom", item.labelOnBottom ?? false);

        if ("events" in item) {
            this.events = item.events;
        }
    }

    makeSubtitleElement() {
        return this.content.createChild(TextValue, {class: "subtitle"}, "div");
    }

    makeDisplayValueElement() {
        return this.content.createChild(TextValue, {class: "display-value"}, "div");
    }

    set(item) {
        for (let key of ["symbol", "displayValue", "subtitle", "hidden", "disabled"]) {
            if (key in item) {
                this[key] = item[key];
            }
        }
    }

    

    /** @param {IconSymbol} symbol*/
    set symbol(symbol) {
        this._symbol = symbol;
        if (symbol !== null && symbol !== undefined) {
            let newSymbol = new GridIconSymbol(symbol, true);
            if (this.symbolElement) {
                this.content.replaceChild(newSymbol, this.symbolElement);
            } else {
                this.content.prepend(newSymbol);
            }
            this.symbolElement = newSymbol;
        } else {
            if (this.symbolElement) {
                this.symbolElement.remove();
            }
            this.symbolElement = null;
            this.symbolLoaded = true;
        }
    }

    get symbol() {
        return this._symbol;
    }

    /** @param {boolean} hidden */
    set hidden(hidden) {
        this._hidden = hidden;
        this.toggleAttribute("i-hidden", hidden);
    }

    get hidden() {
        return this._hidden;
    }

    /** @param {string} value */
    set subtitle(value) {
        this._subtitle = value;
        if (value === null || value === undefined) {
            if (this.subtitleElement) {
                this.subtitleElement.remove();
                this.subtitleElement = null;
            }
        } else {
            if (!this.subtitleElement) {
                this.subtitleElement = this.makeSubtitleElement();
            }
            this.subtitleElement.set(value);

        }
    }
    get subtitle() {
        return this._subtitle;
    }   


    /** @param {string} value */
    set displayValue(value) {
        this._displayValue = value;
        this.displayValueElement.set(value);
    }
    get displayValue() {
        return this._displayValue;
    }


    set utterance(text) {
        this.utteranceText = text;
    }
    get utterance() {
        return this.utteranceText;
    }

    async speak() {
        await this.speakUtterance();
    }


    /** Can be used to wait for the grid symbol image to load.
     *  @return {Promise<void>}
     * */ 
    async waitForLoad(){
        if (!this.loaded) {
            await new Promise((r) => this.onload = () => r());
        }
    }
   
    static get usedStyleSheets(){
        return [
            import.meta.resolve("./grid-icons.css"),
            import.meta.resolve("./themes.css"),
        ]
    }
}

/**
 * @typedef { [number, number] | [number, number, number, number] | [[number,number],[number,number]] } PositionArgs
 */
function parseCellPosition(rowStart, colStart, rowEnd = rowStart, colEnd = colStart) {
    if (Array.isArray(rowStart) && rowStart.length === 2) {
        [rowStart, rowEnd] = rowStart;
    }

    if (Array.isArray(colStart) && colStart.length === 2) {
        [colStart, colEnd] = colStart;
    }

    if (typeof rowStart === "number" && typeof colStart === "number") {
        rowEnd = typeof rowEnd === "number" ? rowEnd+1 : rowStart;
        colEnd = typeof colEnd === "number" ? colEnd+1 : colStart;

        return [rowStart, colStart, rowEnd, colEnd];
    } else {
        return [null, null, null, null];
    }
}

/**
 * A GridLayout represents a grid of GridIcons.
 * It allows adding GridIcons to specific rows and columns.
 * @extends SvgPlus
*/
class GridLayout extends SvgPlus {
    #resizeForced = false;

    /**
     * @param {number} rows - Number of rows in the grid.
     * @param {number} cols - Number of columns in the grid.
     */
    constructor(rows, cols) {
        super("grid-layout");
        this.size = [rows, cols];

        this.resizeObserver = new ResizeObserver(this.onresize.bind(this));
        this.resizeObserver.observe(this);
    }

    /**
     * Sets the size of the grid and updates the CSS grid template accordingly.
     * @param {[number, number]} size - An array containing the number of rows and columns, respectively.
     */
    set size([rows, cols]) {
        if (typeof rows === "number" && typeof cols === "number") {
            this.styles = {
                "grid-template-rows": `repeat(${rows}, 1fr)`,
                "grid-template-columns": `repeat(${cols}, 1fr)`,
                "--rows": rows,
                "--cols": cols
            };
        } 
        this._size = [rows, cols];
    }

    get size() {
      return this._size;
    }


    #forceResize() {
        if (!this.#resizeForced) {
            this.#resizeForced = true;
            window.requestAnimationFrame(() => {
                this.onresize();
                this.#resizeForced = false;
            });
        }
    }


    /**
     * @template {ItemType extends SvgPlus} ItemType
     * 
     * Adds an item to the grid at the specified row and column.
     * @param {ItemType} item - The item to add to the grid.
     * @param {PositionArgs} posArgs - The position arguments specifying the row and column to place the item.
     * 
     * @returns {ItemType} The added item.
     */
    add(item, ...posArgs) {
        let [row, col, rowEnd, colEnd] = parseCellPosition(...posArgs);

        this.#forceResize();
        if (SvgPlus.is(item, GridIcon)) {
            item.getCardBorderRadius = () => this.gridIconBorderRadius;
            item.getCardBorderWidth = () => this.gridIconBorderWidth;
        }
        if (SvgPlus.is(item, SvgPlus) && row !== null) {
            item.styles = {
                "grid-row-start": row + 1,
                "grid-column-start": col + 1,
                "grid-row-end": rowEnd + 1,
                "grid-column-end": colEnd + 1
            };
            this.appendChild(item);
        }

        return item;
    }

    /** Creates a child SvgPlus element, sets its properties and appends it to itself
     * @template {IType extends SvgPlus} IType
     * @param {new (...args: any[]) => IType} classDef class definition of the instances to add.
     * @param {ConstructorParameters<new (...args: any[]) => IType>} item the parameter of the class constructor.
     * @param {PositionArgs} posArgs position arguments specifying the row and column to place the item, same as in add().
     * 
     * @returns {IType} The added item.
   */
    addItemInstance(classDef, item, ...posArgs) {
        let instance = new classDef(item);
        return this.add(instance, ...posArgs);
    }

    /**
     * Adds a GridIcon to the grid at the specified row and column.
     * @param {GridIconOptions} item - The options for the GridIcon to add.
     * @param {PositionArgs} posArgs - The position arguments specifying the row and column to place the item, same as in add().
     * @return {GridIcon} The added GridIcon.
     */
    addGridIcon(item, ...posArgs) {
        const gridIcon = new GridIcon(item);
        return this.add(gridIcon, ...posArgs);
    }


    /**
     * @template {SvgPlus[]|SvgPlus[][]} Items
     * Adds multiple items to the grid at the specified starting row and column.
     * The items can be provided as a 2D array, where each sub-array represents a row of items.
     * @param {Items} items - A 2D array of SvgPlus items or a flat array of SvgPlus items.
     * @param {PositionArgs} posArgs - The position arguments specifying the row and column to place the items, same as in add().
     * 
     * @returns {Items} The added items.
     */
    addItems(items, ...posArgs) {
        if (Array.isArray(items)) {
            let valid = false;
            let items2 = items;
            if (items.every(i => SvgPlus.is(i, SvgPlus) || i == null)) {
                items2 = [items];
                valid = true;
            } else {
                valid = items2.every(row => Array.isArray(row) && row.every(i => SvgPlus.is(i, SvgPlus) || i == null));
            }

            if (valid) {
                let [rowStart, colStart] = parseCellPosition(...posArgs);
                items2.forEach((row, r) => {
                    row.forEach((item, c) => {
                        if (item) {
                            this.add(item, rowStart + r, colStart + c);
                        }
                    });
                });
            }
        }
        return items;
    }

    /** Creates a child SvgPlus element, sets its properties and appends it to itself
     * @template {IType extends SvgPlus} IType
     * @param {new (...args: any[]) => IType} classDef class definition of the instances to add.
     * @param {any[] | any[][] } args the first parameter of the class constructor for each instance to create, can be a 2D array where each sub-array represents a row of items.
     * @param {PositionArgs} posArgs position arguments specifying the row and column to place the items, same as in add().
     * 
     * @returns {IType[][]}
     * 
     * Adds multiple instances of a class to the grid at the specified starting row and column.
     * The items can be provided as a 2D array, where each sub-array represents a row of items.
     * @overload
     * @param {new (...args: any[]) => IType} classDef class definition of the instances to add.
     * @param {any[]  } args the first parameter of the class constructor
     * @param {PositionArgs} posArgs position arguments specifying the row and column to place the items, same as in add().
     * @returns {IType[]}
     * 
     * @overload
     * @param {new (...args: any[]) => IType} classDef class definition of the instances to add.
     * @param {any[][]} args the first parameter of the class constructor for each instance to create, can be a 2D array where each sub-array represents a row of items.
     * @param {PositionArgs} posArgs position arguments specifying the row and column to place the items, same as in add().
     * @returns {IType[][]}
     */
    addItemInstances(classDef, items, ...posArgs) {
        let instances = items.map((item, r) => {
            if (item == null) return null;
            else if (Array.isArray(item)) {
                return item.map(i => i == null ? i : new classDef(i, "item-"+r));
            } else {
                return new classDef(item, "item-"+r);
            }
        });
        this.addItems(instances, ...posArgs);
        return instances;
    }

    /**
     * Adds multiple GridIcons to the grid at the specified starting row and column.
     * The items can be provided as a 2D array, where each sub-array represents a row of items.
     * @param {GridIconOptions[][]|GridIconOptions[]} items - A 2D array of GridIcon options or a flat array of GridIcon options.
     * @param {PositionArgs} posArgs - The position arguments specifying the row and column to place the items, same as in add().
     * @return {GridIcon[][]|GridIcon[]} The added GridIcons.
     * 
     * @overload
     * @param {GridIconOptions[]} items - A flat array of GridIcon options.
     * @param {PositionArgs} posArgs - The position arguments specifying the row and column to place the items, same as in add().
     * @return {GridIcon[]} The added GridIcons.
     * 
     * @overload
     * @param {GridIconOptions[][]} items - A 2D array of GridIcon options, where each sub-array represents a row of items.
     * @param {PositionArgs} posArgs - The position arguments specifying the row and column to place the items, same as in add().
     * @return {GridIcon[][]} The added GridIcons.
     */
    addGridIcons(items, ...posArgs) {
        return this.addItemInstances(GridIcon, items, ...posArgs);
    }

    onresize() {
        this.gridIconBorderRadius = this.clientHeight / 20 / this.size[0];
        this.gridIconBorderWidth = Math.min(Math.max(2, Math.ceil(this.clientWidth / 225)), 4);
        this.styles = {
            "--_grid-icon-border": `${this.gridIconBorderWidth}px`,
            "--width": `${this.clientWidth}px`,
            "--height": `${this.clientHeight}px`
        }
    }
}

export { GridCard, GridLayout, GridIcon, GridIconSymbol, GRID_ICON_THEMES };